# Generated by Django 5.1.6 on 2025-05-12 18:16

import Apl.models.TipDeLaSemana
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=250)),
                ('nombre_completo', models.CharField(max_length=250)),
                ('correo_electronico', models.CharField(max_length=250, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('telefono', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(7)])),
                ('contraseña', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='TipSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Tip')),
                ('contenido', models.TextField(verbose_name='Contenido del Tip')),
                ('imagen', models.ImageField(help_text='Formatos recomendados: JPG, PNG (Max. 2MB)', upload_to='tips/', validators=[Apl.models.TipDeLaSemana.validate_image_size], verbose_name='Imagen del Tip')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tip de la Semana',
                'verbose_name_plural': 'Tips de la Semana',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
                ('primer_nombre', models.CharField(max_length=250)),
                ('segundo_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('primer_apellido', models.CharField(max_length=250)),
                ('segundo_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(7)])),
                ('correo_electronico', models.CharField(max_length=250, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='Apl.administrador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria')], max_length=2)),
                ('documento', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('nombre_mascota', models.CharField(max_length=250)),
                ('correo_electronico', models.CharField(max_length=250, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('telefono', models.CharField(max_length=250)),
                ('recordatorio', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=10)),
                ('horario', models.TimeField()),
                ('extra', models.CharField(blank=True, max_length=250, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Apl.cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=250)),
                ('especie', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250)),
                ('edad', models.CharField(max_length=250)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='Apl.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=250)),
                ('modificacion_servicio', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_mascota', models.CharField(max_length=45)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Apl.cita')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
