# Generated by Django 5.2.1 on 2025-05-16 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0004_alter_servicio_options_remove_servicio_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido_ventana',
            field=models.TextField(verbose_name='Contenido descriptivo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_cuadro',
            field=models.ImageField(upload_to='servicios/cuadros/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen para el cuadro'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_ventana',
            field=models.ImageField(upload_to='servicios/ventanas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen para la ventana'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Título del servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subtitulo_ventana',
            field=models.CharField(max_length=250, verbose_name='Subtítulo en ventana'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo_ventana',
            field=models.CharField(max_length=250, verbose_name='Título en ventana'),
        ),
    ]
