# Generated by Django 5.2.1 on 2025-05-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0005_alter_servicio_contenido_ventana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='mostrar_boton_consulta',
        ),
    ]
