# Generated by Django 5.2.1 on 2025-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0006_remove_servicio_mostrar_boton_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mostrar_boton_consulta',
            field=models.BooleanField(default=True, verbose_name='Mostrar botón de consulta'),
        ),
    ]
