# Generated by Django 5.2.1 on 2025-05-12 19:38

import Apl.models.ModificarGaleria
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Formatos recomendados: JPG, PNG (Max. 2MB)', upload_to='galeria/', validators=[Apl.models.ModificarGaleria.validate_image_size], verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Las imágenes se ordenarán de menor a mayor número', verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Mostrar en galería')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['orden'],
            },
        ),
    ]
