# Generated by Django 5.2.1 on 2025-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0002_imagengaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagengaleria',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (opcional)'),
        ),
    ]
