# Generated by Django 5.2.1 on 2025-05-16 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0003_alter_imagengaleria_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['orden'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='modificacion_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_mascota',
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='contenido_ventana',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido descriptivo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_cuadro',
            field=models.ImageField(default='jpg', upload_to='servicios/cuadros/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen para el cuadro'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_ventana',
            field=models.ImageField(default='jpg', upload_to='servicios/ventanas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen para la ventana'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mostrar_boton_agendar',
            field=models.BooleanField(default=True, verbose_name='Mostrar botón agendar en ventana'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mostrar_boton_consulta',
            field=models.BooleanField(default=True, verbose_name='Mostrar botón de consulta'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='Titulo', max_length=250, verbose_name='Título del servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='subtitulo_ventana',
            field=models.CharField(default='Subtitulo', max_length=250, verbose_name='Subtítulo en ventana'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_ventana',
            field=models.CharField(default='TituloVen', max_length=250, verbose_name='Título en ventana'),
        ),
    ]
